services:
  buildozer:
    image: account-manager
    build: .
    working_dir: /home/user/app
    volumes:
      - .:/home/user/app
      - ${USERPROFILE}/.buildozer:/home/user/.buildozer
    stdin_open: true
    tty: true
