#:import dp kivy.metrics.dp

# 스타일
#:set TEXT_COLOR (0, 0, 0, 1)
<Label>:
    color: TEXT_COLOR

<Button>:
    color: TEXT_COLOR

<ToggleButton>:
    color: TEXT_COLOR

<TextInput>:
    background_color: 1, 1, 1, 1
    foreground_color: TEXT_COLOR

# 본문
<PasswordSettings>:
    on_kv_post: self.initSettings()
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: '비밀번호 설정'
            height: '100dp'
            size_hint_y: None
            font_name: 'Nanum'
            font_size: '30dp'
        BoxLayout:
            padding: '10dp', '10dp' 
            BoxLayout:
                orientation: 'vertical'
                width: '100dp'
                size_hint_x: None
                Label:
                    text: '필수문자 : '
                    font_name: 'Nanum'
                Label:
                    text: '제외문자 : '
                    font_name: 'Nanum'
                Label:
                    text: '길이 : '
                    font_name: 'Nanum'
            BoxLayout:
                orientation: 'vertical'
                GridLayout:
                    cols: 2
                    ToggleButton:
                        id: upperToggle
                        text: '대문자'
                        font_name: 'Nanum'
                        state: 'down'
                    ToggleButton:
                        id: lowerToggle
                        text: '소문자'
                        font_name: 'Nanum'
                        state: 'down'
                    ToggleButton:
                        id: numberToggle
                        text: '숫자'
                        font_name: 'Nanum'
                        state: 'down'
                    ToggleButton:
                        id: specialToggle
                        text: '특수문자'
                        font_name: 'Nanum'
                        state: 'down'
                TextInput:
                    id: excludeTextInput
                    hint_text: '제외할 문자를 입력하세요'
                    font_name: 'Nanum'
                TextInput:
                    id: lengthTextInput
                    text: '10'
                    hint_text: '비밀번호 길이를 입력하세요'
                    font_name: 'Nanum'
        BoxLayout:
            height: '100dp'
            size_hint_y: None
            padding: '10dp', '10dp', '10dp', '50dp'
            Button:
                text: '저장'
                font_name: 'Nanum'
                on_press: root.saveSettings()
            Button:
                text: '취소'
                font_name: 'Nanum'
                on_press: root.manager.current = 'accountList'
